package com.justjava.humanresource.employeeexit.service;

import com.justjava.humanresource.employeeexit.dto.CreateEmployeeExitCommand; import com.justjava.humanresource.employeeexit.dto.UpdateEmployeeExitCommand;
import com.justjava.humanresource.employeeexit.entity.*; import com.justjava.humanresource.employeeexit.enums.*; import com.justjava.humanresource.employeeexit.repository.*;
import com.justjava.humanresource.hr.entity.Employee; import com.justjava.humanresource.hr.repository.EmployeeRepository;
import lombok.RequiredArgsConstructor; import org.flowable.engine.RuntimeService; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor
public class EmployeeExitService {
 private static final EnumSet<ExitStatus> ACTIVE=EnumSet.of(ExitStatus.DRAFT,ExitStatus.SUBMITTED,ExitStatus.IN_APPROVAL,ExitStatus.RETURNED,ExitStatus.APPROVED,ExitStatus.NOTICE_PERIOD,ExitStatus.CLEARANCE_IN_PROGRESS,ExitStatus.SETTLEMENT_IN_PROGRESS,ExitStatus.READY_TO_EXIT,ExitStatus.ON_HOLD);
 private final EmployeeExitCaseRepository exits; private final EmployeeRepository employees; private final ExitClearanceItemRepository clearances; private final ExitAssetReturnRepository assets; private final ExitHandoverItemRepository handovers; private final ExitSettlementRepository settlements; private final EmployeeExitActivityService activity; private final ExitApprovalRouteService approvalRoutes; private final RuntimeService runtimeService;
 @Transactional public EmployeeExitCase create(CreateEmployeeExitCommand c,Long actorId){
  Employee e=employees.findById(c.getEmployeeId()).orElseThrow(()->new IllegalArgumentException("Employee not found."));
  if(exits.existsByEmployeeIdAndStatusIn(e.getId(),ACTIVE))throw new IllegalStateException("The employee already has an active exit case.");
  if(c.getProposedLastWorkingDate().isBefore(c.getNoticeDate()))throw new IllegalArgumentException("Last working date cannot precede notice date.");
  EmployeeExitCase x=new EmployeeExitCase(); x.setExitNumber("EXIT-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());
  x.setEmployeeId(e.getId());x.setInitiatedByEmployeeId(actorId);x.setExitType(c.getExitType());x.setReasonCode(c.getReasonCode().trim());x.setReasonDetails(c.getReasonDetails());x.setRequestDate(LocalDate.now());x.setNoticeDate(c.getNoticeDate());x.setContractualNoticeDays(c.getContractualNoticeDays());x.setNoticeWaivedDays(c.getNoticeWaivedDays());x.setProposedLastWorkingDate(c.getProposedLastWorkingDate());x.setEmploymentStatusBeforeExit(e.getEmploymentStatus());x.setApprovalRouteType(c.getApprovalRouteType());x.setCustomApprovalPathId(c.getCustomApprovalPathId());
  EmployeeExitCase saved=exits.save(x);activity.record(saved.getId(),"CREATED","Exit case created",actorId,null);return saved;
 }
 @Transactional public EmployeeExitCase submit(Long id,Long actorId){EmployeeExitCase x=require(id);if(x.getStatus()!=ExitStatus.DRAFT)throw new IllegalStateException("Only a draft exit can be submitted. Returned exits must continue through their revise task.");var route=approvalRoutes.resolve(x);x.setCurrentApprovalLevel(1);x.setTotalApprovalLevels(route.size());x.setStatus(ExitStatus.IN_APPROVAL);x.setSubmittedAt(LocalDateTime.now());EmployeeExitCase saved=exits.saveAndFlush(x);if(saved.getWorkflowInstanceId()==null){List<String> approvers=route.stream().map(a->String.valueOf(a.getEmployeeId())).toList();Map<String,Object> vars=new HashMap<>();vars.put("exitCaseId",id);vars.put("employeeId",x.getEmployeeId());vars.put("initiatorEmployeeId",String.valueOf(x.getInitiatedByEmployeeId()));vars.put("approverIds",approvers);vars.put("currentApproverId",approvers.get(0));vars.put("currentApprovalIndex",0);vars.put("totalApprovers",approvers.size());var p=runtimeService.startProcessInstanceByKey("employeeExitProcess","EMPLOYEE_EXIT_"+id,vars);saved.setWorkflowInstanceId(p.getProcessInstanceId());}activity.record(id,"SUBMITTED","Exit submitted for approval",actorId,null);return exits.save(saved);}
 @Transactional public boolean applyApprovalDecision(Long id,String decision,Long actorId,String comment,String taskId){EmployeeExitCase x=require(id);boolean more=false;switch(decision){case "APPROVE"->{if(x.getCurrentApprovalLevel()!=null&&x.getTotalApprovalLevels()!=null&&x.getCurrentApprovalLevel()<x.getTotalApprovalLevels()){x.setCurrentApprovalLevel(x.getCurrentApprovalLevel()+1);more=true;}else{x.setStatus(ExitStatus.APPROVED);x.setApprovedAt(LocalDateTime.now());x.setApprovedLastWorkingDate(x.getProposedLastWorkingDate());x.setEffectiveExitDate(x.getProposedLastWorkingDate());}}case "RETURN"->x.setStatus(ExitStatus.RETURNED);case "REJECT"->x.setStatus(ExitStatus.REJECTED);default->throw new IllegalArgumentException("Unsupported exit decision.");}exits.save(x);activity.record(id,"APPROVAL_"+decision,"Exit approval decision: "+decision+(comment==null?"":" - "+comment),actorId,taskId);return more;}
 @Transactional public EmployeeExitCase revise(Long id,UpdateEmployeeExitCommand c,Long actorId,String taskId){EmployeeExitCase x=require(id);if(x.getStatus()!=ExitStatus.RETURNED)throw new IllegalStateException("Only a returned exit can be revised.");if(c.getProposedLastWorkingDate().isBefore(c.getNoticeDate()))throw new IllegalArgumentException("Last working date cannot precede notice date.");x.setReasonCode(c.getReasonCode().trim());x.setReasonDetails(c.getReasonDetails());x.setNoticeDate(c.getNoticeDate());x.setContractualNoticeDays(c.getContractualNoticeDays());x.setNoticeWaivedDays(c.getNoticeWaivedDays());x.setProposedLastWorkingDate(c.getProposedLastWorkingDate());x.setStatus(ExitStatus.IN_APPROVAL);exits.save(x);activity.record(id,"REVISED","Returned exit revised and resubmitted",actorId,taskId);return x;}
 @Transactional public void initializeClearance(Long id){EmployeeExitCase x=require(id);if(x.getStatus()!=ExitStatus.APPROVED)return;x.setStatus(ExitStatus.CLEARANCE_IN_PROGRESS);exits.save(x);for(ClearanceType t:ClearanceType.values())clearances.findByExitCaseIdAndClearanceType(id,t).orElseGet(()->{ExitClearanceItem i=new ExitClearanceItem();i.setExitCaseId(id);i.setClearanceType(t);i.setOwnerGroup(group(t));i.setDueDate(x.getEffectiveExitDate());return clearances.save(i);});activity.record(id,"CLEARANCE_INITIALIZED","Exit clearance workstreams initialized",null,null);}
 @Transactional public ExitClearanceItem completeClearance(Long exitId,ClearanceType type,ClearanceStatus status,String comments,Long actorId,String taskId){if(status!=ClearanceStatus.CLEARED&&status!=ClearanceStatus.CLEARED_WITH_EXCEPTION&&status!=ClearanceStatus.WAIVED)throw new IllegalArgumentException("Clearance must use a terminal outcome.");if(type==ClearanceType.MANAGER_HANDOVER&&handovers.existsByExitCaseIdAndCompletedFalse(exitId))throw new IllegalStateException("All handover items must be completed first.");if(type==ClearanceType.ASSET_AND_FACILITIES&&assets.findByExitCaseIdOrderByAssetName(exitId).stream().anyMatch(a->a.getDisposition()==AssetDisposition.PENDING))throw new IllegalStateException("Every assigned asset requires a terminal disposition.");if(type==ClearanceType.PAYROLL_AND_FINANCE&&settlements.findFirstByExitCaseIdOrderBySettlementVersionDesc(exitId).filter(s->s.getStatus()==SettlementStatus.POSTED||s.getStatus()==SettlementStatus.PAYMENT_PENDING||s.getStatus()==SettlementStatus.PAID).isEmpty())throw new IllegalStateException("Final settlement must be posted to payroll before payroll clearance.");ExitClearanceItem i=clearances.findByExitCaseIdAndClearanceType(exitId,type).orElseThrow();i.setStatus(status);i.setComments(comments);i.setCompletedByEmployeeId(actorId);i.setCompletedAt(LocalDateTime.now());i.setFlowableTaskId(taskId);activity.record(exitId,"CLEARANCE_COMPLETED",type+" completed as "+status,actorId,taskId);return clearances.save(i);}
 @Transactional public boolean evaluateReadiness(Long id){boolean pending=clearances.existsByExitCaseIdAndStatusNotIn(id,List.of(ClearanceStatus.CLEARED,ClearanceStatus.CLEARED_WITH_EXCEPTION,ClearanceStatus.WAIVED));EmployeeExitCase x=require(id);if(!pending){x.setStatus(ExitStatus.READY_TO_EXIT);x.setClearanceCompletedAt(LocalDateTime.now());exits.save(x);}return !pending;}
 @Transactional public EmployeeExitCase cancel(Long id,String reason,Long actorId){EmployeeExitCase x=require(id);if(EnumSet.of(ExitStatus.COMPLETED,ExitStatus.REJECTED,ExitStatus.CANCELLED).contains(x.getStatus()))throw new IllegalStateException("This exit can no longer be cancelled.");x.setStatus(ExitStatus.CANCELLED);x.setCancelledAt(LocalDateTime.now());x.setCancellationReason(reason);exits.save(x);if(x.getWorkflowInstanceId()!=null)runtimeService.deleteProcessInstance(x.getWorkflowInstanceId(),"Exit cancelled");activity.record(id,"CANCELLED","Exit cancelled: "+reason,actorId,null);return x;}
 @Transactional(readOnly=true) public EmployeeExitCase require(Long id){return exits.findById(id).orElseThrow(()->new IllegalArgumentException("Exit case not found."));}
 private String group(ClearanceType t){return switch(t){case MANAGER_HANDOVER->"departmentHead";case ASSET_AND_FACILITIES->"assetManager";case IT_AND_SECURITY->"admin";case HR_AND_LEGAL->"humanResource";case PAYROLL_AND_FINANCE->"financialOfficers";};}
}
