package com.justjava.humanresource.employeeexit.service;
import com.justjava.humanresource.employeeexit.entity.*; import com.justjava.humanresource.employeeexit.enums.AssetDisposition; import com.justjava.humanresource.employeeexit.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.*;
@Service @RequiredArgsConstructor public class ExitOperationsService {
 private final EmployeeExitService exits; private final ExitAssetReturnRepository assets; private final ExitHandoverItemRepository handovers; private final EmployeeExitActivityService activity;
 @Transactional public ExitAssetReturn addAsset(Long exitId,String externalId,String code,String name,String category,BigDecimal value){exits.require(exitId);ExitAssetReturn a=new ExitAssetReturn();a.setExitCaseId(exitId);a.setExternalAssetId(externalId);a.setExternalAssetCode(code);a.setAssetName(name);a.setCategory(category);a.setAssessedValue(value);return assets.save(a);}
 @Transactional public ExitAssetReturn disposeAsset(Long exitId,Long assetId,AssetDisposition disposition,BigDecimal recovery,String condition,Long actor){ExitAssetReturn a=assets.findById(assetId).orElseThrow();if(!a.getExitCaseId().equals(exitId))throw new IllegalArgumentException("Asset does not belong to this exit.");if(disposition==AssetDisposition.PENDING)throw new IllegalArgumentException("Select a terminal asset disposition.");if(disposition==AssetDisposition.RECOVER_FROM_SETTLEMENT&&(recovery==null||recovery.signum()<0))throw new IllegalArgumentException("A recovery amount is required.");a.setDisposition(disposition);a.setRecoveryAmount(recovery);a.setReturnCondition(condition);a.setReturnedDate(disposition==AssetDisposition.RETURNED?LocalDate.now():null);a.setVerifiedByEmployeeId(actor);a.setVerifiedAt(LocalDateTime.now());activity.record(exitId,"ASSET_DISPOSITION","Asset "+a.getAssetName()+" marked "+disposition,actor,null);return assets.save(a);}
 @Transactional public ExitHandoverItem addHandover(Long exitId,String subject,String details,Long successor){exits.require(exitId);ExitHandoverItem h=new ExitHandoverItem();h.setExitCaseId(exitId);h.setSubject(subject);h.setDetails(details);h.setSuccessorEmployeeId(successor);return handovers.save(h);}
 @Transactional public ExitHandoverItem completeHandover(Long exitId,Long itemId,Long actor){ExitHandoverItem h=handovers.findById(itemId).orElseThrow();if(!h.getExitCaseId().equals(exitId))throw new IllegalArgumentException("Handover item does not belong to this exit.");h.setCompleted(true);h.setVerifiedByEmployeeId(actor);h.setVerifiedAt(LocalDateTime.now());activity.record(exitId,"HANDOVER_COMPLETED","Handover item completed: "+h.getSubject(),actor,null);return handovers.save(h);}
}
