package com.justjava.humanresource.employeeexit.service;
import com.justjava.humanresource.employeeexit.dto.SettlementLineCommand; import com.justjava.humanresource.employeeexit.entity.*; import com.justjava.humanresource.employeeexit.enums.*; import com.justjava.humanresource.employeeexit.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class ExitSettlementService {
 private final ExitSettlementRepository settlements; private final ExitSettlementLineRepository lines; private final ExitAssetReturnRepository assets; private final EmployeeExitService exitService; private final EmployeeExitCaseRepository exits; private final EmployeeExitActivityService activity; private final ExitPackageCalculationService packageCalculation;
 @Transactional public ExitSettlement calculateFromPackage(Long exitId,List<SettlementLineCommand> manualLines,BigDecimal monthlyBasic,BigDecimal leaveDays,Long actorId){EmployeeExitCase x=exitService.require(exitId);List<SettlementLineCommand> generated=new ArrayList<>(packageCalculation.calculate(x,monthlyBasic,leaveDays));if(manualLines!=null)generated.addAll(manualLines);return calculate(exitId,generated,actorId);}
 @Transactional public ExitSettlement calculate(Long exitId,List<SettlementLineCommand> commands,Long actorId){EmployeeExitCase x=exitService.require(exitId);if(x.getStatus()==ExitStatus.COMPLETED)throw new IllegalStateException("A completed exit cannot be recalculated.");List<SettlementLineCommand> all=new ArrayList<>(commands==null?List.of():commands);assets.findByExitCaseIdOrderByAssetName(exitId).stream().filter(a->a.getDisposition()==AssetDisposition.RECOVER_FROM_SETTLEMENT&&a.getRecoveryAmount()!=null).forEach(a->{SettlementLineCommand c=new SettlementLineCommand();c.setLineType(SettlementLineType.ASSET_RECOVERY);c.setDescription("Asset recovery: "+a.getAssetName());c.setAmount(a.getRecoveryAmount());c.setEarning(false);c.setSource("EXIT_ASSET_"+a.getId());all.add(c);});if(all.isEmpty())throw new IllegalArgumentException("At least one settlement line is required.");int version=settlements.findFirstByExitCaseIdOrderBySettlementVersionDesc(exitId).map(s->s.getSettlementVersion()+1).orElse(1);ExitSettlement s=new ExitSettlement();s.setExitCaseId(exitId);s.setSettlementVersion(version);s.setCutoffDate(x.getEffectiveExitDate()!=null?x.getEffectiveExitDate():x.getProposedLastWorkingDate());s.setCalculatedByEmployeeId(actorId);s.setCalculatedAt(LocalDateTime.now());s.setStatus(SettlementStatus.CALCULATED);ExitSettlement saved=settlements.saveAndFlush(s);BigDecimal earnings=BigDecimal.ZERO,deductions=BigDecimal.ZERO;for(SettlementLineCommand c:all){if(c.isManualAdjustment()&&(c.getAdjustmentReason()==null||c.getAdjustmentReason().isBlank()))throw new IllegalArgumentException("Manual adjustments require a reason.");ExitSettlementLine l=new ExitSettlementLine();l.setSettlementId(saved.getId());l.setLineType(c.getLineType());l.setComponentCode(c.getComponentCode());l.setDescription(c.getDescription());l.setAmount(c.getAmount().setScale(2,RoundingMode.HALF_UP));l.setEarning(c.isEarning());l.setTaxable(c.isTaxable());l.setManualAdjustment(c.isManualAdjustment());l.setAdjustmentReason(c.getAdjustmentReason());l.setSource(c.getSource());lines.save(l);if(c.isEarning())earnings=earnings.add(l.getAmount());else deductions=deductions.add(l.getAmount());}saved.setGrossEarnings(earnings);saved.setTotalDeductions(deductions);saved.setNetSettlement(earnings.subtract(deductions));saved.setCalculationFingerprint(Integer.toHexString(Objects.hash(exitId,version,earnings,deductions,saved.getCutoffDate())));saved.setStatus(SettlementStatus.IN_APPROVAL);x.setStatus(ExitStatus.SETTLEMENT_IN_PROGRESS);exits.save(x);activity.record(exitId,"SETTLEMENT_CALCULATED","Settlement version "+version+" calculated",actorId,null);return settlements.save(saved);}
 @Transactional public ExitSettlement approve(Long settlementId,Long actorId){ExitSettlement s=settlements.findById(settlementId).orElseThrow();if(s.getStatus()!=SettlementStatus.IN_APPROVAL)throw new IllegalStateException("Only a settlement in approval can be approved.");s.setStatus(SettlementStatus.APPROVED);s.setApprovedByEmployeeId(actorId);s.setApprovedAt(LocalDateTime.now());EmployeeExitCase x=exitService.require(s.getExitCaseId());x.setSettlementCompletedAt(LocalDateTime.now());exits.save(x);activity.record(x.getId(),"SETTLEMENT_APPROVED","Final settlement approved",actorId,null);return settlements.save(s);}
}
