package com.justjava.humanresource.employeeexit;
import org.junit.jupiter.api.Test; import javax.xml.parsers.DocumentBuilderFactory; import java.util.*; import static org.junit.jupiter.api.Assertions.*;
class EmployeeExitProcessDefinitionTest {
 private static final String NS="http://www.omg.org/spec/BPMN/20100524/MODEL";
 @Test void processHasApprovalParallelClearanceEffectiveDateAndFinalization()throws Exception{var d=parse();assertEquals("employeeExitProcess",d.getElementsByTagNameNS(NS,"process").item(0).getAttributes().getNamedItem("id").getNodeValue());assertIds(d,"userTask",Set.of("exitApproval","reviseExit","managerClearance","assetClearance","itClearance","hrClearance","payrollClearance","resolveExceptions"));assertIds(d,"serviceTask",Set.of("applyDecision","initializeClearance","evaluateReadiness","finalizeEmployment","revokeAccess","completeExit"));assertIds(d,"parallelGateway",Set.of("clearanceFork","clearanceJoin"));assertIds(d,"intermediateCatchEvent",Set.of("effectiveDateWait"));}
 @Test void accessRevocationIsAsyncAndRetryable()throws Exception{var d=parse();var nodes=d.getElementsByTagNameNS(NS,"serviceTask");org.w3c.dom.Element revoke=null;for(int i=0;i<nodes.getLength();i++)if("revokeAccess".equals(nodes.item(i).getAttributes().getNamedItem("id").getNodeValue()))revoke=(org.w3c.dom.Element)nodes.item(i);assertNotNull(revoke);assertEquals("true",revoke.getAttributeNS("http://flowable.org/bpmn","async"));assertEquals("R3/PT30S",revoke.getElementsByTagNameNS("http://flowable.org/bpmn","failedJobRetryTimeCycle").item(0).getTextContent());}
 private org.w3c.dom.Document parse()throws Exception{try(var in=getClass().getResourceAsStream("/processes/employeeExitProcess.bpmn")){assertNotNull(in);var f=DocumentBuilderFactory.newInstance();f.setNamespaceAware(true);return f.newDocumentBuilder().parse(in);}}
 private void assertIds(org.w3c.dom.Document d,String type,Set<String> expected){var n=d.getElementsByTagNameNS(NS,type);Set<String> ids=new HashSet<>();for(int i=0;i<n.getLength();i++)ids.add(n.item(i).getAttributes().getNamedItem("id").getNodeValue());assertTrue(ids.containsAll(expected),()->"Missing "+type+": "+expected+" from "+ids);}
}
