package com.justjava.humanresource.employeeexit;
import com.justjava.humanresource.core.enums.EmploymentStatus; import com.justjava.humanresource.employeeexit.dto.CreateEmployeeExitCommand; import com.justjava.humanresource.employeeexit.entity.EmployeeExitCase; import com.justjava.humanresource.employeeexit.enums.*; import com.justjava.humanresource.employeeexit.repository.*; import com.justjava.humanresource.employeeexit.service.*; import com.justjava.humanresource.hr.entity.Employee; import com.justjava.humanresource.hr.repository.EmployeeRepository; import org.flowable.engine.RuntimeService; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import java.time.*; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(org.mockito.junit.jupiter.MockitoExtension.class) class EmployeeExitServiceTest {
 @Mock EmployeeExitCaseRepository exits; @Mock EmployeeRepository employees; @Mock ExitClearanceItemRepository clearances; @Mock ExitAssetReturnRepository assets; @Mock ExitHandoverItemRepository handovers; @Mock ExitSettlementRepository settlements; @Mock EmployeeExitActivityService activity; @Mock ExitApprovalRouteService approvalRoutes; @Mock RuntimeService runtime;
 EmployeeExitService service;
 @BeforeEach void setUp(){service=new EmployeeExitService(exits,employees,clearances,assets,handovers,settlements,activity,approvalRoutes,runtime);}
 @Test void createsAuditableDraftForActiveEmployee(){Employee e=Employee.builder().employeeNumber("E1").firstName("Ada").lastName("Okafor").employmentStatus(EmploymentStatus.ACTIVE).build();e.setId(7L);when(employees.findById(7L)).thenReturn(Optional.of(e));when(exits.existsByEmployeeIdAndStatusIn(eq(7L),anyCollection())).thenReturn(false);when(exits.save(any())).thenAnswer(i->{EmployeeExitCase x=i.getArgument(0);x.setId(11L);return x;});CreateEmployeeExitCommand c=command();EmployeeExitCase x=service.create(c,9L);assertEquals(ExitStatus.DRAFT,x.getStatus());assertEquals(EmploymentStatus.ACTIVE,x.getEmploymentStatusBeforeExit());assertTrue(x.getExitNumber().startsWith("EXIT-"));verify(activity).record(11L,"CREATED","Exit case created",9L,null);}
 @Test void rejectsSecondActiveExit(){Employee e=Employee.builder().employeeNumber("E1").firstName("Ada").lastName("Okafor").employmentStatus(EmploymentStatus.ACTIVE).build();e.setId(7L);when(employees.findById(7L)).thenReturn(Optional.of(e));when(exits.existsByEmployeeIdAndStatusIn(eq(7L),anyCollection())).thenReturn(true);assertThrows(IllegalStateException.class,()->service.create(command(),9L));}
 @Test void rejectsInvalidExitDates(){Employee e=Employee.builder().employeeNumber("E1").firstName("Ada").lastName("Okafor").employmentStatus(EmploymentStatus.ACTIVE).build();e.setId(7L);when(employees.findById(7L)).thenReturn(Optional.of(e));CreateEmployeeExitCommand c=command();c.setProposedLastWorkingDate(c.getNoticeDate().minusDays(1));assertThrows(IllegalArgumentException.class,()->service.create(c,9L));}
 @Test void reviseReturnedExitKeepsExistingWorkflow(){EmployeeExitCase x=new EmployeeExitCase();x.setId(11L);x.setStatus(ExitStatus.RETURNED);x.setWorkflowInstanceId("process-1");when(exits.findById(11L)).thenReturn(Optional.of(x));var c=new com.justjava.humanresource.employeeexit.dto.UpdateEmployeeExitCommand();c.setReasonCode("REVISED");c.setNoticeDate(LocalDate.now());c.setProposedLastWorkingDate(LocalDate.now().plusDays(20));c.setContractualNoticeDays(20);c.setNoticeWaivedDays(0);service.revise(11L,c,7L,"task-1");assertEquals(ExitStatus.IN_APPROVAL,x.getStatus());assertEquals("process-1",x.getWorkflowInstanceId());verifyNoInteractions(runtime);verify(activity).record(11L,"REVISED","Returned exit revised and resubmitted",7L,"task-1");}
 private CreateEmployeeExitCommand command(){CreateEmployeeExitCommand c=new CreateEmployeeExitCommand();c.setEmployeeId(7L);c.setExitType(ExitType.RESIGNATION);c.setReasonCode("PERSONAL");c.setNoticeDate(LocalDate.now());c.setProposedLastWorkingDate(LocalDate.now().plusDays(30));c.setContractualNoticeDays(30);c.setNoticeWaivedDays(0);return c;}
}
