package com.justjava.humanresource.employeeexit.enums;
public enum ExitStatus { DRAFT, SUBMITTED, IN_APPROVAL, RETURNED, APPROVED, NOTICE_PERIOD, CLEARANCE_IN_PROGRESS, SETTLEMENT_IN_PROGRESS, READY_TO_EXIT, COMPLETED, REJECTED, CANCELLED, ON_HOLD }
