package com.justjava.humanresource.request.service;

import com.justjava.humanresource.approval.enums.ApprovalModuleType;
import com.justjava.humanresource.approval.model.*;
import com.justjava.humanresource.approval.service.ApprovalRouteResolverFactory;
import com.justjava.humanresource.core.config.AuthenticationManager;
import com.justjava.humanresource.hr.entity.Employee;
import com.justjava.humanresource.hr.service.EmployeeService;
import com.justjava.humanresource.request.dto.*;
import com.justjava.humanresource.request.entity.*;
import com.justjava.humanresource.request.enums.*;
import com.justjava.humanresource.request.handler.*;
import com.justjava.humanresource.request.repository.*;
import com.justjava.humanresource.workflow.dto.FlowableTaskDTO;
import com.justjava.humanresource.workflow.service.FlowableTaskService;
import lombok.RequiredArgsConstructor;
import org.flowable.engine.RuntimeService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;

@Service @RequiredArgsConstructor
public class WorkflowRequestService {
 private final WorkflowRequestRepository requestRepository; private final WorkflowRequestTypeRepository typeRepository; private final WorkflowRequestItemRepository itemRepository; private final WorkflowRequestAttachmentRepository attachmentRepository; private final WorkflowRequestApprovalStepRepository stepRepository; private final WorkflowRequestCommentRepository commentRepository; private final WorkflowRequestActivityRepository activityRepository; private final StaffRequisitionDetailRepository staffRepository; private final FileRequestDetailRepository fileRepository; private final AssetRequestDetailRepository assetRepository; private final WorkflowRequestHandlerRegistry handlers; private final RequestNumberService numberService; private final WorkflowRequestActivityService activityService; private final EmployeeService employeeService; private final AuthenticationManager auth; private final ApprovalRouteResolverFactory routeFactory; private final RuntimeService runtimeService; private final FlowableTaskService taskService;
 @Transactional public WorkflowRequest createDraft(CreateWorkflowRequestCommand command){Employee actor=currentEmployee();WorkflowRequestType config=type(command.getRequestType());handlers.get(command.getRequestType()).validate(command);WorkflowRequest r=new WorkflowRequest();r.setRequestNumber(numberService.next(command.getRequestType()));r.setRequestType(command.getRequestType());r.setTitle(command.getTitle().trim());r.setDescription(command.getDescription());r.setPriority(command.getPriority()==null?RequestPriority.NORMAL:command.getPriority());r.setRequesterEmployeeId(actor.getId());r.setDepartmentId(command.getDepartmentId()!=null?command.getDepartmentId():actor.getDepartment()==null?null:actor.getDepartment().getId());r.setStatus(RequestStatus.DRAFT);r=requestRepository.save(r);handlers.get(r.getRequestType()).saveDetails(r,command);saveItems(r,command.getItems());activityService.record(r.getId(),RequestActivityType.CREATED,"Request draft created",actor.getId());return r;}
 @Transactional public WorkflowRequest createAndSubmit(CreateWorkflowRequestCommand command){WorkflowRequest r=createDraft(command);return submit(r.getId());}
 @Transactional public WorkflowRequest submit(Long id){WorkflowRequest r=owned(id);if(!(r.getStatus()==RequestStatus.DRAFT||r.getStatus()==RequestStatus.RETURNED_FOR_CORRECTION))throw new IllegalStateException("Only draft or returned requests can be submitted.");WorkflowRequestType config=type(r.getRequestType());if(config.isRequiresAttachment()&&attachmentRepository.countByWorkflowRequestId(id)==0)throw new IllegalStateException("An attachment is required before submission.");if(config.isSupportsItems()&&itemRepository.countByWorkflowRequestId(id)==0)throw new IllegalStateException("At least one item is required before submission.");handlers.get(r.getRequestType()).beforeSubmit(r);r.setStatus(RequestStatus.SUBMITTED);r.setSubmittedAt(LocalDateTime.now());r=requestRepository.save(r);if(!config.isRequiresApproval()){r.setStatus(RequestStatus.APPROVED);r.setApprovedAt(LocalDateTime.now());handlers.get(r.getRequestType()).afterApproved(r);activityService.record(id,RequestActivityType.APPROVED,"Request automatically approved",r.getRequesterEmployeeId());return requestRepository.save(r);}ApprovalContext context=ApprovalContext.builder().moduleType(ApprovalModuleType.REQUEST).requesterEmployeeId(r.getRequesterEmployeeId()).moduleRefId(r.getId()).build();List<ApproverRef> route=routeFactory.getResolver(context).resolveApprovers(context);if(route.isEmpty())throw new IllegalStateException("No approval route is configured for this requester.");List<String> approvers=route.stream().map(a->String.valueOf(a.getEmployeeId())).toList();r.setCurrentApprovalLevel(1);r.setTotalApprovalLevels(approvers.size());r.setStatus(RequestStatus.IN_APPROVAL);r=requestRepository.save(r);Map<String,Object> vars=new HashMap<>(handlers.get(r.getRequestType()).buildWorkflowVariables(r));vars.put("workflowRequestId",r.getId());vars.put("requestType",r.getRequestType().name());vars.put("requesterEmployeeId",r.getRequesterEmployeeId());vars.put("approverIds",approvers);vars.put("totalLevels",approvers.size());var pi=runtimeService.startProcessInstanceByKey(config.getProcessDefinitionKey(),"REQUEST_"+r.getId(),vars);r.setWorkflowInstanceId(pi.getProcessInstanceId());activityService.record(id,RequestActivityType.SUBMITTED,"Request submitted for approval",r.getRequesterEmployeeId());return requestRepository.save(r);}
 @Transactional(readOnly=true) public List<WorkflowRequest> myRequests(){return requestRepository.findByRequesterEmployeeIdOrderByCreatedAtDesc(currentEmployee().getId());}
 @Transactional(readOnly=true) public List<WorkflowRequest> visibleRequests(){return isHrAdmin()?requestRepository.findAllByOrderByCreatedAtDesc():myRequests();}
 @Transactional(readOnly=true) public List<WorkflowRequest> allRequests(){requireHrAdmin();return requestRepository.findAllByOrderByCreatedAtDesc();}
 @Transactional(readOnly=true) public List<FlowableTaskDTO> pendingTasks(){Employee e=currentEmployee();return taskService.getTasksForAssigneeAcrossProcesses(String.valueOf(e.getId()),requestProcessKeys());}
 @Transactional(readOnly=true) public Map<String,Object> context(){Employee e=currentEmployee();return Map.of("employeeId",e.getId(),"hrAdmin",isHrAdmin(),"canCreate",true);}
 @Transactional(readOnly=true) public WorkflowRequestDetailDTO details(Long id){WorkflowRequest r=visible(id);Object typed=switch(r.getRequestType()){case STAFF_REQUISITION->staffRepository.findByWorkflowRequestId(id).orElse(null);case FILE_REQUEST->fileRepository.findByWorkflowRequestId(id).orElse(null);case ASSET_REQUEST->assetRepository.findByWorkflowRequestId(id).orElse(null);case GENERAL_REQUEST->null;};List<WorkflowRequestComment> comments=commentRepository.findByWorkflowRequestIdOrderByCreatedAt(id);if(!isHrAdmin())comments=comments.stream().filter(c->!c.isInternalOnly()).toList();return WorkflowRequestDetailDTO.builder().request(r).typeDetails(typed).items(itemRepository.findByWorkflowRequestIdOrderById(id)).attachments(attachmentRepository.findByWorkflowRequestIdOrderByCreatedAt(id)).approvalSteps(stepRepository.findByWorkflowRequestIdOrderBySequenceNo(id)).comments(comments).activities(activityRepository.findByWorkflowRequestIdOrderByCreatedAt(id)).build();}
 @Transactional public void approve(String taskId,String comment){complete(taskId,"APPROVE",comment);}
 @Transactional public void reject(String taskId,String comment){if(comment==null||comment.isBlank())throw new IllegalArgumentException("A rejection comment is required.");complete(taskId,"REJECT",comment);}
 @Transactional public void returnForCorrection(String taskId,String comment){if(comment==null||comment.isBlank())throw new IllegalArgumentException("A return comment is required.");complete(taskId,"RETURN",comment);}
 @Transactional public WorkflowRequest cancel(Long id){WorkflowRequest r=owned(id);if(EnumSet.of(RequestStatus.APPROVED,RequestStatus.REJECTED,RequestStatus.CANCELLED,RequestStatus.CLOSED).contains(r.getStatus()))throw new IllegalStateException("This request can no longer be cancelled.");if(r.getWorkflowInstanceId()!=null)runtimeService.deleteProcessInstance(r.getWorkflowInstanceId(),"Cancelled by requester");r.setStatus(RequestStatus.CANCELLED);activityService.record(id,RequestActivityType.CANCELLED,"Request cancelled",r.getRequesterEmployeeId());return requestRepository.save(r);}
 @Transactional public WorkflowRequest close(Long id){requireHrAdmin();WorkflowRequest r=requestRepository.findById(id).orElseThrow(()->new IllegalArgumentException("Request not found."));if(r.getStatus()!=RequestStatus.APPROVED)throw new IllegalStateException("Only approved requests can be closed.");r.setStatus(RequestStatus.CLOSED);r.setClosedAt(LocalDateTime.now());activityService.record(id,RequestActivityType.CLOSED,"Request closed",currentEmployee().getId());return requestRepository.save(r);}
 @Transactional public WorkflowRequestComment addComment(Long id,String text,boolean internal){if(text==null||text.isBlank())throw new IllegalArgumentException("Comment is required.");WorkflowRequest r=visible(id);Employee actor=currentEmployee();if(internal&&!isHrAdmin())throw new IllegalStateException("Only HR or administrators may add internal comments.");WorkflowRequestComment c=new WorkflowRequestComment();c.setWorkflowRequestId(id);c.setComment(text.trim());c.setCommentedByEmployeeId(actor.getId());c.setInternalOnly(internal);c=commentRepository.save(c);activityService.record(id,RequestActivityType.COMMENTED,"Comment added",actor.getId());return c;}
 public Employee currentEmployee(){Object email=auth.get("email");if(email==null)throw new IllegalStateException("Authenticated user has no email claim.");return employeeService.getByEmail(String.valueOf(email));}
 public WorkflowRequest visible(Long id){WorkflowRequest r=requestRepository.findById(id).orElseThrow(()->new IllegalArgumentException("Request not found."));Long actor=currentEmployee().getId();if(r.getRequesterEmployeeId().equals(actor)||isHrAdmin()||stepRepository.findByWorkflowRequestIdOrderBySequenceNo(id).stream().anyMatch(s->s.getApproverEmployeeId().equals(actor)))return r;throw new IllegalStateException("You are not authorized to view this request.");}
 private void complete(String taskId,String decision,String comment){Employee actor=currentEmployee();if(!taskService.isTaskAssignedTo(taskId,String.valueOf(actor.getId())))throw new IllegalStateException("Task is not assigned to current user.");Map<String,Object> vars=new HashMap<>();vars.put("approvalDecision",decision);vars.put("approvalComment",comment);vars.put("approvalActorId",actor.getId());vars.put("flowableTaskId",taskId);taskService.completeTask(taskId,vars);}
 private WorkflowRequest owned(Long id){WorkflowRequest r=requestRepository.findById(id).orElseThrow(()->new IllegalArgumentException("Request not found."));if(!r.getRequesterEmployeeId().equals(currentEmployee().getId()))throw new IllegalStateException("You do not own this request.");return r;}
 private WorkflowRequestType type(RequestType type){WorkflowRequestType t=typeRepository.findByCode(type.name()).orElseThrow(()->new IllegalStateException("Request type is not configured: "+type));if(!t.isEnabled())throw new IllegalStateException("Request type is disabled.");return t;}
 private void saveItems(WorkflowRequest r,List<CreateWorkflowRequestCommand.Item> items){if(items==null)return;for(var p:items){WorkflowRequestItem i=new WorkflowRequestItem();i.setWorkflowRequestId(r.getId());i.setItemName(p.getItemName());i.setDescription(p.getDescription());i.setCategory(p.getCategory());i.setQuantity(p.getQuantity());i.setUnitOfMeasure(p.getUnitOfMeasure());i.setEstimatedUnitCost(p.getEstimatedUnitCost());i.setEstimatedTotalCost(p.getEstimatedUnitCost()==null?null:p.getEstimatedUnitCost().multiply(p.getQuantity()));i.setCurrency(p.getCurrency()==null?null:p.getCurrency().toUpperCase(Locale.ROOT));i.setVendorName(p.getVendorName());i.setRemarks(p.getRemarks());itemRepository.save(i);}}
 private Set<String> requestProcessKeys(){Set<String> keys=typeRepository.findByEnabledTrueOrderByName().stream().map(WorkflowRequestType::getProcessDefinitionKey).filter(Objects::nonNull).filter(k->!k.isBlank()).collect(java.util.stream.Collectors.toCollection(LinkedHashSet::new));return keys.isEmpty()?Set.of("genericRequestApprovalProcess"):keys;}
 public boolean isHrAdmin(){return auth.isHumanResource()||auth.isJobHR()||auth.isAdmin()||auth.isRestrictedHr();} private void requireHrAdmin(){if(!isHrAdmin())throw new IllegalStateException("HR or administrator access is required.");}
}
