package com.justjava.humanresource.employeeexit.controller;
import com.justjava.humanresource.core.config.AuthenticationManager; import com.justjava.humanresource.employeeexit.dto.CreateEmployeeExitCommand; import com.justjava.humanresource.employeeexit.dto.UpdateEmployeeExitCommand; import com.justjava.humanresource.employeeexit.enums.*; import com.justjava.humanresource.employeeexit.repository.*; import com.justjava.humanresource.employeeexit.service.*; import com.justjava.humanresource.hr.entity.*; import com.justjava.humanresource.hr.repository.EmployeeRepository; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*;
@Controller @RequestMapping("/employee/exit") @RequiredArgsConstructor public class EmployeeExitSelfServiceController {
 private final EmployeeExitService service; private final EmployeeExitDocumentService documentService; private final EmployeeExitReadinessService readiness; private final EmployeeExitAuthorizationService authorization; private final EmployeeExitCaseRepository exits; private final ExitClearanceItemRepository clearances; private final ExitActivityRepository activities; private final EmployeeExitDocumentRepository documents; private final EmployeeRepository employees; private final org.flowable.engine.TaskService taskService; private final AuthenticationManager auth;
 @GetMapping public String home(Model m){Employee e=current();m.addAttribute("title","My Exit Request");m.addAttribute("employee",e);m.addAttribute("exits",exits.findByEmployeeIdOrderByCreatedAtDesc(e.getId()));return "employees/exit";}
 @PostMapping public String create(@Valid @ModelAttribute CreateEmployeeExitCommand c){Employee e=current();c.setEmployeeId(e.getId());c.setExitType(ExitType.RESIGNATION);var x=service.create(c,e.getId());return "redirect:/employee/exit/"+x.getId();}
 @GetMapping("/{id}") public String detail(@PathVariable Long id,Model m){Employee e=current();var x=service.require(id);if(!x.getEmployeeId().equals(e.getId()))throw new IllegalStateException("You may only view your own exit request.");m.addAttribute("title",x.getExitNumber());m.addAttribute("exit",x);m.addAttribute("clearances",clearances.findByExitCaseIdOrderByClearanceType(id));m.addAttribute("activities",activities.findByExitCaseIdOrderByCreatedAt(id));m.addAttribute("documents",documents.findByExitCaseIdOrderByUploadedAtDesc(id));m.addAttribute("documentTypes",ExitDocumentType.values());m.addAttribute("readiness",readiness.validate(id));m.addAttribute("reviseTask",x.getWorkflowInstanceId()==null?null:taskService.createTaskQuery().processInstanceId(x.getWorkflowInstanceId()).taskDefinitionKey("reviseExit").active().singleResult());return "employees/exit-detail";}
 @PostMapping("/{id}/submit") public String submit(@PathVariable Long id){Employee e=current();var x=service.require(id);if(!x.getEmployeeId().equals(e.getId()))throw new IllegalStateException("You may only submit your own exit request.");service.submit(id,e.getId());return "redirect:/employee/exit/"+id;}
 @PostMapping("/{id}/tasks/{taskId}/revise") public String revise(@PathVariable Long id,@PathVariable String taskId,@Valid @ModelAttribute UpdateEmployeeExitCommand c){Employee e=current();var x=service.require(id);if(!x.getEmployeeId().equals(e.getId()))throw new IllegalStateException("You may only revise your own exit request.");var t=taskService.createTaskQuery().taskId(taskId).active().singleResult();if(t==null||!"reviseExit".equals(t.getTaskDefinitionKey())||!t.getProcessInstanceId().equals(x.getWorkflowInstanceId()))throw new IllegalStateException("Invalid exit revision task.");service.revise(id,c,e.getId(),taskId);taskService.complete(taskId);return "redirect:/employee/exit/"+id;}
 @PostMapping(value="/{id}/documents",consumes=org.springframework.http.MediaType.MULTIPART_FORM_DATA_VALUE) public String uploadDocument(@PathVariable Long id,@RequestParam ExitDocumentType documentType,@RequestParam("file")org.springframework.web.multipart.MultipartFile file){Employee e=current();documentService.upload(id,documentType,ExitDocumentVisibility.EMPLOYEE_AND_HR,file,e,authorization);return "redirect:/employee/exit/"+id;}
 @GetMapping("/{id}/documents/{documentId}") public org.springframework.http.ResponseEntity<byte[]> downloadDocument(@PathVariable Long id,@PathVariable Long documentId){EmployeeDocument d=documentService.download(id,documentId,current(),authorization);return org.springframework.http.ResponseEntity.ok().contentType(org.springframework.http.MediaType.parseMediaType(d.getFileType()==null?"application/octet-stream":d.getFileType())).header(org.springframework.http.HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+d.getFileName()+"\"").body(d.getFileData());}
 private Employee current(){Object email=auth.get("email");if(email==null)throw new IllegalStateException("Authenticated user has no email claim.");return employees.findByEmail(email.toString()).orElseThrow(()->new IllegalStateException("Employee record not found."));}
}
