package com.justjava.humanresource.employeeexit.controller;
import com.justjava.humanresource.employeeexit.dto.*; import com.justjava.humanresource.employeeexit.entity.EmployeeExitCase; import com.justjava.humanresource.employeeexit.enums.*; import com.justjava.humanresource.employeeexit.repository.*; import com.justjava.humanresource.employeeexit.service.*; import com.justjava.humanresource.hr.repository.EmployeeRepository; import com.justjava.humanresource.hr.entity.Employee;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.flowable.engine.TaskService; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.util.*;
@Controller @RequestMapping("/employee-exits") @RequiredArgsConstructor public class EmployeeExitController {
 private final EmployeeExitService exitService; private final ExitOperationsService operations; private final ExitAssetSnapshotService assetSnapshotService; private final ExitSettlementService settlements; private final ExitPayrollImpactService payrollImpact; private final EmployeeExitDocumentService documentService; private final EmployeeExitReadinessService readiness; private final EmployeeExitReportService reports; private final ExitPackageConfigurationService packageConfiguration; private final EmployeeExitAuthorizationService authorization; private final EmployeeExitCaseRepository exitRepository; private final ExitClearanceItemRepository clearanceRepository; private final ExitAssetReturnRepository assetRepository; private final ExitHandoverItemRepository handoverRepository; private final ExitSettlementRepository settlementRepository; private final ExitSettlementLineRepository lineRepository; private final EmployeeExitDocumentRepository documentRepository; private final ExitActivityRepository activityRepository; private final EmployeeRepository employeeRepository; private final ExitPackageComponentRepository packageComponentRepository; private final ExitPackageRuleRepository packageRuleRepository; private final com.justjava.humanresource.payroll.repositories.PayrollPeriodRepository payrollPeriodRepository; private final TaskService taskService;
 @GetMapping public String list(Model m){authorization.require(authorization.isHr(),"HR access is required.");m.addAttribute("title","Employee Exits");m.addAttribute("subTitle","Clearance, final settlement and offboarding");m.addAttribute("exits",exitRepository.findAllByOrderByCreatedAtDesc());m.addAttribute("pending",exitRepository.countByStatus(ExitStatus.CLEARANCE_IN_PROGRESS));return "employee-exit/list";}
 @GetMapping("/new") public String createPage(Model m){authorization.require(authorization.isHr(),"HR access is required.");m.addAttribute("title","Start Employee Exit");m.addAttribute("employees",employeeRepository.findAllVisible());m.addAttribute("exitTypes",ExitType.values());return "employee-exit/new";}
 @PostMapping public String create(@Valid @ModelAttribute CreateEmployeeExitCommand c){var actor=authorization.currentEmployee();authorization.require(authorization.isHr()&&authorization.canCreateFor(c.getEmployeeId(),actor),"HR access is required.");var x=exitService.create(c,actor.getId());return "redirect:/employee-exits/"+x.getId();}
 @PostMapping("/{id}/submit") public String submit(@PathVariable Long id){var x=exitService.require(id);var actor=authorization.currentEmployee();authorization.require(authorization.isHr()&&authorization.canSubmit(x,actor),"HR access is required.");exitService.submit(id,actor.getId());return redirect(id);}
 @PostMapping("/{id}/cancel") public String cancel(@PathVariable Long id,@RequestParam String reason){authorization.require(authorization.isHr(),"HR access is required.");exitService.cancel(id,reason,currentEmployeeId());return redirect(id);}
 @GetMapping("/{id}") public String detail(@PathVariable Long id,Model m){var x=exitService.require(id);var actor=authorization.currentEmployee();var tasks=x.getWorkflowInstanceId()==null?List.<org.flowable.task.api.Task>of():taskService.createTaskQuery().processInstanceId(x.getWorkflowInstanceId()).active().list();authorization.require(authorization.canViewOperationalExit(x,actor,tasks),"Employee exit workflow access is required.");var visibleDocuments=documentRepository.findByExitCaseIdOrderByUploadedAtDesc(id).stream().filter(d->authorization.canViewDocument(x,d,actor)).toList();m.addAttribute("title",x.getExitNumber());m.addAttribute("exit",x);m.addAttribute("employee",employeeRepository.findById(x.getEmployeeId()).orElseThrow());m.addAttribute("clearances",clearanceRepository.findByExitCaseIdOrderByClearanceType(id));m.addAttribute("assets",assetRepository.findByExitCaseIdOrderByAssetName(id));m.addAttribute("handovers",handoverRepository.findByExitCaseIdOrderByCreatedAt(id));var ss=settlementRepository.findByExitCaseIdOrderBySettlementVersionDesc(id);m.addAttribute("settlements",ss);m.addAttribute("settlementLines",ss.isEmpty()?List.of():lineRepository.findBySettlementIdOrderById(ss.get(0).getId()));m.addAttribute("documents",visibleDocuments);m.addAttribute("readiness",readiness.validate(id));m.addAttribute("payrollPeriods",payrollPeriodRepository.findByCompanyIdOrderByPeriodStartDesc(x.getCompanyId()));m.addAttribute("activities",activityRepository.findByExitCaseIdOrderByCreatedAt(id));m.addAttribute("tasks",tasks);m.addAttribute("taskActions",taskActions(x,tasks,actor));m.addAttribute("documentTypes",ExitDocumentType.values());m.addAttribute("documentVisibilities",ExitDocumentVisibility.values());addWorkflowLayoutAttributes(m,actor);m.addAttribute("canViewSettlementSection",authorization.canViewSettlementSection(actor));m.addAttribute("canUseSettlementActions",authorization.canUseSettlementActions(actor));m.addAttribute("canViewAssetSection",authorization.canViewAssetSection(actor));m.addAttribute("canUseAssetActions",authorization.canUseAssetActions(actor));m.addAttribute("canViewHandoverSection",authorization.canViewHandoverSection(actor));m.addAttribute("canUseHandoverActions",authorization.canUseHandoverActions(actor));m.addAttribute("canViewDocumentSection",authorization.isHr()||!visibleDocuments.isEmpty());m.addAttribute("canManageDocuments",authorization.isHr());m.addAttribute("canResolveExceptions",authorization.canResolveExceptions(actor));m.addAttribute("currentActorEmployeeId",actor.getId());m.addAttribute("currentActorEmployeeIdString",String.valueOf(actor.getId()));return "employee-exit/detail";}
 @PostMapping("/{id}/tasks/{taskId}/decision") public String decision(@PathVariable Long id,@PathVariable String taskId,@RequestParam String decision,@RequestParam(required=false)String comment){var x=exitService.require(id);var t=requireTask(id,taskId);var actor=authorization.currentEmployee();authorization.require(authorization.canApprove(x,t,actor),"This approval task is not assigned to you.");taskService.complete(taskId,Map.of("exitDecision",decision,"exitComment",comment==null?"":comment,"exitActorId",actor.getId(),"flowableTaskId",taskId));return redirect(id);}
 @PostMapping("/{id}/tasks/{taskId}/revise") public String revise(@PathVariable Long id,@PathVariable String taskId,@Valid @ModelAttribute UpdateEmployeeExitCommand command){authorization.require(authorization.isHr(),"HR access is required.");var t=requireTask(id,taskId);if(!"reviseExit".equals(t.getTaskDefinitionKey()))throw new IllegalStateException("This is not an exit revision task.");exitService.revise(id,command,currentEmployeeId(),taskId);taskService.complete(taskId);return redirect(id);}
 @PostMapping("/{id}/tasks/{taskId}/clearance") public String clearance(@PathVariable Long id,@PathVariable String taskId,@RequestParam ClearanceStatus status,@RequestParam(required=false)String comments){var t=requireTask(id,taskId);ClearanceType type=clearanceType(t.getTaskDefinitionKey());var actor=authorization.currentEmployee();authorization.require(authorization.canCompleteClearance(type,actor),"You are not authorized for this clearance task.");exitService.completeClearance(id,type,status,comments,actor.getId(),taskId);taskService.complete(taskId);return redirect(id);}
 @PostMapping("/{id}/tasks/{taskId}/resolve-exceptions") public String resolveExceptions(@PathVariable Long id,@PathVariable String taskId){authorization.require(authorization.isHr(),"HR access is required.");var t=requireTask(id,taskId);if(!"resolveExceptions".equals(t.getTaskDefinitionKey()))throw new IllegalStateException("This is not a resolve-exceptions task.");var result=readiness.validate(id);if(!result.ready())throw new IllegalStateException("Readiness blockers remain: "+result.summary());taskService.complete(taskId);return redirect(id);}
 @PostMapping("/{id}/assets") public String addAsset(@PathVariable Long id,@RequestParam String externalAssetId,@RequestParam(required=false)String externalAssetCode,@RequestParam String assetName,@RequestParam(required=false)String category,@RequestParam(required=false)BigDecimal assessedValue){authorization.require(authorization.isHr()||authorization.canManageAssets(),"Asset or HR access is required.");operations.addAsset(id,externalAssetId,externalAssetCode,assetName,category,assessedValue);return redirect(id);}
 @PostMapping("/{id}/assets/sync") public String syncAssets(@PathVariable Long id){authorization.require(authorization.canManageAssets()||authorization.isHr(),"Asset or HR access is required.");assetSnapshotService.snapshotAssignedAssets(id);return redirect(id);}
 @PostMapping("/{id}/assets/{assetId}/dispose") public String dispose(@PathVariable Long id,@PathVariable Long assetId,@RequestParam AssetDisposition disposition,@RequestParam(required=false)BigDecimal recoveryAmount,@RequestParam(required=false)String condition){authorization.require(authorization.canManageAssets()||authorization.isHr(),"Asset or HR access is required.");operations.disposeAsset(id,assetId,disposition,recoveryAmount,condition,currentEmployeeId());return redirect(id);}
 @PostMapping("/{id}/handovers") public String handover(@PathVariable Long id,@RequestParam String subject,@RequestParam(required=false)String details,@RequestParam(required=false)Long successorEmployeeId){var actor=authorization.currentEmployee();authorization.require(authorization.canUseHandoverActions(actor),"Manager handover access is required.");operations.addHandover(id,subject,details,successorEmployeeId);return redirect(id);}
 @PostMapping("/{id}/handovers/{itemId}/complete") public String completeHandover(@PathVariable Long id,@PathVariable Long itemId){var actor=authorization.currentEmployee();authorization.require(authorization.canUseHandoverActions(actor),"Manager handover access is required.");operations.completeHandover(id,itemId,actor.getId());return redirect(id);}
 @PostMapping("/{id}/settlements") public String calculate(@PathVariable Long id,@Valid @ModelAttribute SettlementLineCommand line){authorization.require(authorization.canManageSettlement(),"Finance access is required.");settlements.calculate(id,List.of(line),currentEmployeeId());return redirect(id);}
 @PostMapping("/{id}/settlements/package") public String calculatePackage(@PathVariable Long id,@RequestParam(defaultValue="0")BigDecimal monthlyBasic,@RequestParam(defaultValue="0")BigDecimal leaveDays){authorization.require(authorization.canManageSettlement(),"Finance access is required.");settlements.calculateFromPackage(id,List.of(),monthlyBasic,leaveDays,currentEmployeeId());return redirect(id);}
 @PostMapping("/{id}/settlements/{settlementId}/approve") public String approveSettlement(@PathVariable Long id,@PathVariable Long settlementId){authorization.require(authorization.canManageSettlement(),"Finance access is required.");settlements.approve(settlementId,currentEmployeeId());return redirect(id);}
 @GetMapping("/{id}/settlements/{settlementId}/payroll-preview") public String payrollPreview(@PathVariable Long id,@PathVariable Long settlementId,Model m){authorization.require(authorization.canManageSettlement(),"Finance access is required.");var x=exitService.require(id);var actor=authorization.currentEmployee();addWorkflowLayoutAttributes(m,actor);m.addAttribute("title","Exit Payroll Preview");m.addAttribute("subTitle",x.getExitNumber());m.addAttribute("exit",x);m.addAttribute("settlementId",settlementId);m.addAttribute("preview",payrollImpact.preview(settlementId));m.addAttribute("payrollPeriods",payrollPeriodRepository.findByCompanyIdOrderByPeriodStartDesc(x.getCompanyId()));return "employee-exit/payroll-preview";}
 @PostMapping("/{id}/settlements/{settlementId}/post") public String postSettlement(@PathVariable Long id,@PathVariable Long settlementId,@RequestParam Long payrollPeriodId){authorization.require(authorization.canManageSettlement(),"Finance access is required.");payrollImpact.postApprovedSettlement(settlementId,payrollPeriodId,currentEmployeeId());return redirect(id);}
 @PostMapping(value="/{id}/documents",consumes=org.springframework.http.MediaType.MULTIPART_FORM_DATA_VALUE) public String uploadDocument(@PathVariable Long id,@RequestParam ExitDocumentType documentType,@RequestParam(defaultValue="EMPLOYEE_AND_HR")ExitDocumentVisibility visibility,@RequestParam("file")org.springframework.web.multipart.MultipartFile file){var actor=authorization.currentEmployee();documentService.upload(id,documentType,visibility,file,actor,authorization);return redirect(id);}
 @GetMapping("/{id}/documents/{documentId}") public org.springframework.http.ResponseEntity<byte[]> downloadDocument(@PathVariable Long id,@PathVariable Long documentId){var d=documentService.download(id,documentId,authorization.currentEmployee(),authorization);return org.springframework.http.ResponseEntity.ok().contentType(org.springframework.http.MediaType.parseMediaType(d.getFileType()==null?"application/octet-stream":d.getFileType())).header(org.springframework.http.HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+d.getFileName()+"\"").body(d.getFileData());}
 @PostMapping("/{id}/documents/{documentId}/delete") public String deleteDocument(@PathVariable Long id,@PathVariable Long documentId){var actor=authorization.currentEmployee();var doc=documentRepository.findById(documentId).orElseThrow();authorization.require(authorization.canDeleteDocument(exitService.require(id),doc,actor),"HR access is required to delete exit documents.");documentService.delete(id,documentId,actor.getId());return redirect(id);}
 @GetMapping("/reports") public String reportPage(@ModelAttribute ExitReportFilter filter,Model m){authorization.require(authorization.canViewReports(),"Exit report access is required.");var actor=authorization.currentEmployee();addWorkflowLayoutAttributes(m,actor);m.addAttribute("title","Exit Reports");m.addAttribute("subTitle","Operational status, settlement liability and recoveries");m.addAttribute("filter",filter);m.addAttribute("summary",reports.summary(filter));m.addAttribute("statuses",exitService.uiVisibleStatuses());m.addAttribute("exitTypes",ExitType.values());return "employee-exit/reports";}
 @GetMapping("/api/reports/summary") @ResponseBody public ExitDashboardSummary reportSummary(@ModelAttribute ExitReportFilter filter){authorization.require(authorization.canViewReports(),"Exit report access is required.");return reports.summary(filter);}
 @GetMapping("/settings/package-components") public String packageSettings(Model m){authorization.require(authorization.isHr()||authorization.canManageSettlement(),"HR or finance access is required.");var actor=authorization.currentEmployee();addWorkflowLayoutAttributes(m,actor);m.addAttribute("title","Exit Package Settings");m.addAttribute("subTitle","Settlement components and calculation rules");m.addAttribute("components",packageComponentRepository.findAll());m.addAttribute("rules",packageRuleRepository.findAll());m.addAttribute("lineTypes",SettlementLineType.values());m.addAttribute("calculationMethods",ExitPackageCalculationMethod.values());m.addAttribute("exitTypes",ExitType.values());return "employee-exit/package-components";}
 @PostMapping("/settings/package-components") public String savePackageComponent(@Valid @ModelAttribute ExitPackageComponentCommand command){authorization.require(authorization.isHr()||authorization.canManageSettlement(),"HR or finance access is required.");packageConfiguration.saveComponent(command);return "redirect:/employee-exits/settings/package-components";}
 @PostMapping("/settings/package-rules") public String savePackageRule(@Valid @ModelAttribute ExitPackageRuleCommand command){authorization.require(authorization.isHr()||authorization.canManageSettlement(),"HR or finance access is required.");packageConfiguration.saveRule(command);return "redirect:/employee-exits/settings/package-components";}
 private org.flowable.task.api.Task requireTask(Long id,String taskId){var x=exitService.require(id);var t=taskService.createTaskQuery().taskId(taskId).active().singleResult();if(t==null||!Objects.equals(t.getProcessInstanceId(),x.getWorkflowInstanceId()))throw new IllegalStateException("Task does not belong to this exit.");return t;}
 private ClearanceType clearanceType(String key){return switch(key){case"managerClearance"->ClearanceType.MANAGER_HANDOVER;case"assetClearance"->ClearanceType.ASSET_AND_FACILITIES;case"itClearance"->ClearanceType.IT_AND_SECURITY;case"hrClearance"->ClearanceType.HR_AND_LEGAL;case"payrollClearance"->ClearanceType.PAYROLL_AND_FINANCE;default->throw new IllegalStateException("Unsupported clearance task.");};}
 private List<TaskActionView> taskActions(EmployeeExitCase x,List<org.flowable.task.api.Task> tasks,Employee actor){return tasks.stream().map(t->new TaskActionView(t,authorization.canApprove(x,t,actor),"reviseExit".equals(t.getTaskDefinitionKey())&&authorization.isHr(),canCompleteClearanceTask(t.getTaskDefinitionKey(),actor),"resolveExceptions".equals(t.getTaskDefinitionKey())&&authorization.canResolveExceptions(actor))).filter(TaskActionView::canAct).toList();}
 private boolean canCompleteClearanceTask(String key,Employee actor){return switch(key){case"managerClearance"->authorization.canCompleteClearance(ClearanceType.MANAGER_HANDOVER,actor);case"assetClearance"->authorization.canCompleteClearance(ClearanceType.ASSET_AND_FACILITIES,actor);case"itClearance"->authorization.canCompleteClearance(ClearanceType.IT_AND_SECURITY,actor);case"hrClearance"->authorization.canCompleteClearance(ClearanceType.HR_AND_LEGAL,actor);case"payrollClearance"->authorization.canCompleteClearance(ClearanceType.PAYROLL_AND_FINANCE,actor);default->false;};}
 public static class TaskActionView{private final org.flowable.task.api.Task task;private final boolean approvalTask;private final boolean revisionTask;private final boolean clearanceTask;private final boolean resolveExceptionsTask;TaskActionView(org.flowable.task.api.Task task,boolean approvalTask,boolean revisionTask,boolean clearanceTask,boolean resolveExceptionsTask){this.task=task;this.approvalTask=approvalTask;this.revisionTask=revisionTask;this.clearanceTask=clearanceTask;this.resolveExceptionsTask=resolveExceptionsTask;}public org.flowable.task.api.Task getTask(){return task;}public boolean isApprovalTask(){return approvalTask;}public boolean isRevisionTask(){return revisionTask;}public boolean isClearanceTask(){return clearanceTask;}public boolean isResolveExceptionsTask(){return resolveExceptionsTask;}public boolean canAct(){return approvalTask||revisionTask||clearanceTask||resolveExceptionsTask;}}
 private Long currentEmployeeId(){return authorization.currentEmployee().getId();}
 private String redirect(Long id){return "redirect:/employee-exits/"+id;}
 private void addWorkflowLayoutAttributes(Model m,Employee actor){m.addAttribute("userName",actor.getFullName());m.addAttribute("canActAsHr",authorization.isHr());m.addAttribute("canActAsAdmin",authorization.isAdmin());m.addAttribute("canActAsDepartmentHead",authorization.isDepartmentHead());m.addAttribute("canManageSettlement",authorization.canManageSettlement());m.addAttribute("canManageAssets",authorization.canManageAssets());m.addAttribute("canSeeExitList",authorization.isHr());m.addAttribute("canSeeExitReports",authorization.canViewReports());m.addAttribute("canSeeAssignedAssets",authorization.canManageAssets());m.addAttribute("canSeePackageSettings",authorization.isHr()||authorization.canManageSettlement());}
}
