package com.justjava.humanresource.employeeexit.controller;
import com.justjava.humanresource.employeeexit.dto.EmployeeAssignedAssetCommand; import com.justjava.humanresource.employeeexit.service.EmployeeAssignedAssetService; import com.justjava.humanresource.employeeexit.service.EmployeeExitAuthorizationService; import com.justjava.humanresource.hr.repository.EmployeeRepository; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import java.util.List;
@Controller @RequestMapping("/employee-exits/assigned-assets") @RequiredArgsConstructor public class EmployeeAssignedAssetController {
    private final EmployeeAssignedAssetService assignedAssets; private final EmployeeExitAuthorizationService authorization; private final EmployeeRepository employeeRepository;
    @GetMapping public String page(@RequestParam(required=false) Long employeeId,Model m){authorization.require(authorization.canManageAssets(),"Asset manager, HR, or admin access is required.");var actor=authorization.currentEmployee();addWorkflowLayoutAttributes(m,actor);m.addAttribute("title","Assigned Assets");m.addAttribute("subTitle","Local assigned-asset source for exit sync");m.addAttribute("employees",employeeRepository.findAllVisible());m.addAttribute("selectedEmployeeId",employeeId);m.addAttribute("assets",employeeId==null?List.of():assignedAssets.findByEmployee(employeeId));return "employee-exit/assigned-assets";}
    @PostMapping public String add(@Valid @ModelAttribute EmployeeAssignedAssetCommand command){authorization.require(authorization.canManageAssets(),"Asset manager, HR, or admin access is required.");assignedAssets.addOrUpdate(command);return "redirect:/employee-exits/assigned-assets?employeeId="+command.getEmployeeId();}
    @PostMapping("/{id}/deactivate") public String deactivate(@PathVariable Long id,@RequestParam Long employeeId){authorization.require(authorization.canManageAssets(),"Asset manager, HR, or admin access is required.");assignedAssets.setActive(id,false);return "redirect:/employee-exits/assigned-assets?employeeId="+employeeId;}
    private void addWorkflowLayoutAttributes(Model m,com.justjava.humanresource.hr.entity.Employee actor){m.addAttribute("userName",actor.getFullName());m.addAttribute("canActAsHr",authorization.isHr());m.addAttribute("canActAsAdmin",authorization.isAdmin());m.addAttribute("canActAsDepartmentHead",authorization.isDepartmentHead());m.addAttribute("canManageSettlement",authorization.canManageSettlement());m.addAttribute("canManageAssets",authorization.canManageAssets());m.addAttribute("canSeeExitList",authorization.isHr());m.addAttribute("canSeeExitReports",authorization.canViewReports());m.addAttribute("canSeeAssignedAssets",authorization.canManageAssets());m.addAttribute("canSeePackageSettings",authorization.isHr()||authorization.canManageSettlement());}
}
